[project]
name = "my-automatization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastexcel>=0.12.0",
    "minijinja>=2.2.0",
    "polars>=1.12.0",
    "pywin32>=308",
]
